class ComboSerializer < ActiveModel::Serializer
  attributes :id, :image_urls, :youtube_id, :starter, :location, :hit_type, :meterless, :author_notes, :damage, :inputs, :user_id
  
  def image_urls
    object.inputs.split(' ').map do |input|
      
      case input
        when '1'
          'https://i.imgur.com/Fby15hF.png'
        when '2'
          'https://i.imgur.com/KezFbHr.png'
        when '3'
          'https://i.imgur.com/06D3AyK.png'
        when '4'
          'https://i.imgur.com/HwKpXDr.png'
        when '5'
          'https://i.imgur.com/OfO6HKV.png'
        when '6'
          'https://i.imgur.com/gyfnDrv.png'
        when '7'
          'https://i.imgur.com/2rO9chH.png'
        when '8'
          'https://i.imgur.com/8fY51s7.png'
        when '9'
          'https://i.imgur.com/UqYEenq.png'
        when '214'
          'https://i.imgur.com/F0hNuQt.png'
        when '236'
          'https://i.imgur.com/FGoSIYq.png'
        when '421'
          'https://i.imgur.com/XUhyVUc.png'
        when '623'
          'https://i.imgur.com/YbO0z8X.png'
        when '248'
          'https://i.imgur.com/X6EeTeb.png'
        when '268'
          'https://i.imgur.com/CCdla7s.png'
        when '426'
          'https://i.imgur.com/eoQSkqs.png'
        when '624'
          'https://i.imgur.com/iocDwKJ.png'
        when '684'
          'https://i.imgur.com/4Iem06x.png'
        when '486'
          'https://i.imgur.com/oKZq3p4.png'
        when '842'
          'https://i.imgur.com/ogiRqdN.png'
        when '862'
          'https://i.imgur.com/7d2vQ51.png'
        when 'Circle'
          'https://i.imgur.com/SoCvJ4j.png'
        when '['
          'https://i.imgur.com/rXmq6Ps.png'
        when ']'
          'https://i.imgur.com/HgDolUR.png'
        when 'j.'
          'https://i.imgur.com/X4u3eOL.png'
        when 'jc.'
          'https://i.imgur.com/gnDR9rY.png'
        when 'dj.'
          'https://i.imgur.com/zTALYJv.png'
        when 'sj.'
          'https://i.imgur.com/o8VUuQr.png'
        when 'dl.'
          'https://i.imgur.com/3Yiy3t1.png'
        when 'md.'
          'https://i.imgur.com/e92KV5m.png'
        when 'tk.'
          'https://i.imgur.com/dDhnIA9.png'
        when 'land'
          'https://i.imgur.com/KTDY9lc.png'
        when 'OTG'
          'https://i.imgur.com/hE5DELK.png'
        else
          if object.character.game.slug === "ggst"
            case input
              when '-'
                'https://i.imgur.com/IxEwf4u.png'
              when 'P'
                'https://i.imgur.com/Dv8VQDw.png'
              when 'K'
                'https://i.imgur.com/8AKrxRf.png'
              when 'S'
                'https://i.imgur.com/KtvFf0G.png'
              when 'H'
                'https://i.imgur.com/Ki3AR78.png'
              when 'D'
                'https://i.imgur.com/iolwA1k.png'
              when 'RC'
                'https://i.imgur.com/ovXavcY.png'
              when 'Dash'
                'https://i.imgur.com/TuBfI2x.png'
              when 'c.'
                'https://i.imgur.com/hd22b7L.png'
              when 'f.'
                'https://i.imgur.com/8ux6pvT.png'
              when 'ws.'
                'https://i.imgur.com/uDCpULE.png'
              end
          elsif object.character.game.slug === "sf6"
            case input
              when '-'
                'https://i.imgur.com/IxEwf4u.png'
              when 'LP'
                'https://i.imgur.com/aCCMFrY.png'
              when 'MP'
                'https://i.imgur.com/ptI0QQ8.png'
              when 'HP'
                'https://i.imgur.com/AREXTeF.png'
              when 'LK'
                'https://i.imgur.com/Mc2G0nT.png'
              when 'MK'
                'https://i.imgur.com/NHrJZfc.png'
              when 'HK'
                'https://i.imgur.com/VuPrTtO.png'
              when 'DI'
                'https://i.imgur.com/TnDZpg0.png'
              when 'DR'
                'https://i.imgur.com/46kbAU5.png'
              else
            end
            # add more elsif for games here
          end
      end
    end
  end

end
